config/routes.rb
Rails.application.routes.draw do
  # Routes for static pages
  get 'privacy-policy', to: 'static_pages#privacy_policy', as: 'privacy_policy'
  get 'terms-of-service', to: 'static_pages#terms_of_service', as: 'terms_of_service'
  get 'about', to: 'static_pages#about'

  post 'user/create'
  get 'user/new_staff', to: 'user#new_staff', as: :new_staff
  get 'user/new_student', to: 'user#new_student', as: :new_student
  get 'user/profile'
  post 'user/edit'
  post 'user/:id/resend_invite', to: 'user#resend_invite', as: :resend_invite

  root 'homescreen#show'

  get 'login', to: 'sessions#new'
  resource :session

  resources :passwords, param: :token

  resources :comments, only: [:create] do
    member do
      patch 'soft_delete'
    end
  end

  resources :courses, only: %i[index show new create destroy] do
    member do
      get 'add_students'
      post 'handle_add_students'
      get 'add_lecturers'
      post 'handle_add_lecturers'
      get 'settings'
      post 'handle_settings'
      get 'export_csv'
      get 'profile/:participant_id/:participant_type', to: 'courses#profile', as: 'participant_profile'
      get 'details', to: 'courses#details'
      post 'import_details'
    end

    resources :projects, only: %i[show edit update create new] do
      member do
        patch :change_status
      end
      collection do
        get 'selected_topic', to: 'projects#selected_topic'
        get 'selected_topic_edit', to: 'projects#selected_topic_edit'
      end

      resources :progress_updates, only: %i[show edit update create new destroy]
    end

    resources :topics, only: %i[index show edit update create new destroy] do
      member do
        patch :change_status
      end
    end

    resources :participants, only: [:index]

    resources :lecturers, only: %i[index show] do
      member do
        patch 'promote_to_coordinator'
        patch 'demote_to_lecturer'
      end

      resources :projects, only: [:show], controller: 'projects'

      resources :topics, only: %i[index show edit update create new] do
        member do
          patch :change_status
        end
      end
    end

    resource :project_template, only: %i[edit update show]
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/topic.rb
class Topic < ApplicationRecord
  self.table_name = 'projects'

  enum :ownership_type, { student: 0, project_group: 1, lecturer: 2 }
  default_scope { where(ownership_type: :lecturer) }

  belongs_to :course
  belongs_to :owner, polymorphic: true

  has_many :topic_instances, dependent: :destroy, foreign_key: 'project_id'

  has_many :proposed_project_instances, class_name: 'ProjectInstance', foreign_key: 'source_topic_id'

  # DO NOT WRITE TO STATUS IN PROJECTS, IT'S ONLY MEANT TO KEEP TRACK OF THE STATUS OF THE LATEST PROJECT INSTANCE
  # write to the latest project instance instead
  attribute :status, :integer, default: :pending
  enum :status, { pending: 0, approved: 1, rejected: 2, redo: 3, not_submitted: 4 }

  # Status filters
  scope :pending, -> { where(status: :pending) }
  scope :approved, -> { where(status: :approved) }
  scope :rejected, -> { where(status: :rejected) }
  scope :pending_redo, -> { where(status: %i[pending redo]) }
  scope :proposals, -> { where(status: %i[pending redo rejected]) }

  before_validation :set_ownership_type

  def supervisor
    User.find(Enrolment.find(enrolment_id).user_id)
  end

  def member
    if ownership.owner.is_a?(ProjectGroup)
      ownership.owner.users
    else
      [ownership.user]
    end
  end

  def current_instance
    if topic_instances.column_names.include?('version')
      topic_instances.order(version: :desc, created_at: :desc).first
    else
      topic_instances.order(created_at: :desc).first
    end
  end

  def current_status
    (current_instance&.status || status || :not_submitted).to_s
  end

  def current_title
    current_instance&.title || title
  end

  private

  def set_ownership_type
    self.ownership_type = :lecturer
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_course
  before_action :set_topic, only: [:show, :edit, :update, :destroy, :change_status]
  before_action -> { authorize @topic }, only: [:show, :edit, :update, :destroy, :change_status]

  def index
    @topics = policy_scope(@course.topics)
    search if params[:query].present?
  end

  def show
    @instances = @topic.topic_instances.order(version: :asc)
    @owner = @topic.owner
    @status = @topic.current_instance&.status
    @members = @owner.is_a?(ProjectGroup) ? @owner.users : [@owner]
    @is_coordinator = @course.enrolments.exists?(user: current_user, role: :coordinator)

    if @owner.is_a?(ProjectGroup)
      @members = @owner.users  #All memebers if group project
    else
      @members = [@owner] #individual
    end
    if params[:lecturer_id]
      @lecturer = User.find(params[:lecturer_id])
    end
    if !params[:version].blank?
      @index = params[:version].to_i
    else
      @index = @instances.size
    end
    if @index <= 0 || @index > @instances.size
      @index = @instances.size
    end

    @current_instance = @instances[@index - 1]
    @current_version = @index
    @latest_version = @instances.size

    if @current_instance.nil?
      redirect_to course_path(@course), alert: "No project instance available."
      return
    end

  @current_fields = @current_instance.project_instance_fields.includes(:project_template_field).order(project_template_field_id: :asc)
  @next_fields = nil

  if @index < @instances.size
    @next_instance = @instances[@index]
    @next_fields = @next_instance.project_instance_fields.includes(:project_template_field).order(project_template_field_id: :asc)
  end

  @comments = @current_instance.comments.order(created_at: :asc)
    @new_comment = Comment.new(user: current_user, location: @current_instance)
    @fields = @current_instance.project_instance_fields.includes(:project_template_field).order(project_template_field_id: :asc)
  end

  def change_status
    authorize @topic

    current_instance = @topic.current_instance
    current_instance.update!(
      status: params[:status],
      last_status_change_time: Time.current,
      last_status_change_by: current_user.id
    )

    GeneralMailer.with(
      username: @topic.owner.username,
      email_address: @topic.owner.email_address,
      course: @course,
      topic: @topic,
      supervisor_username: Current.user.username
    ).Topic_Status_Updated.deliver_later

    redirect_to course_topic_path(@course, @topic), notice: "Status updated."
  end

  def edit
    @instance = @topic.topic_instances.last || @topic.topic_instances.build

    @existing_values = @instance.project_instance_fields.each_with_object({}) do |f, h|
      h[f.project_template_field_id] = f.value
    end

    @template_fields = @course.project_template.project_template_fields.where(applicable_to: [:topics, :both])
  end

  def update
    has_coordinator_comment = false

    coordinator_ids = @course.coordinators.pluck(:id)

    @topic.topic_instances.last.comments.each do |comment|
      if coordinator_ids.include? comment.user_id
        has_coordinator_comment = true
        break
      end
    end

    begin
      ActiveRecord::Base.transaction do
        status = @course.require_coordinator_approval ? :pending : :approved
        current_status = @topic.current_instance&.status&.to_sym

        if current_status == :rejected || current_status == :redo || (current_status == :pending && has_coordinator_comment)
          version = @topic.topic_instances.count + 1
          @instance = @topic.topic_instances.build(version: version, created_by: current_user, status: status)
        else
          @instance = @topic.topic_instances.last
        end
        
        if !params[:fields].present?
          raise StandardError
        end

        # Set title
        title_field_id = params[:fields].keys.first if params[:fields].present?
        @instance.title = params[:fields][title_field_id] if title_field_id.present?

        @instance.last_edit_time = Time.current
        @instance.last_edit_by = current_user.id
        
        if !@instance.save
          raise StandardError
        end

        params[:fields].each do |field_id, value|
          existing_field = ProjectInstanceField.find_by(
            project_template_field_id: field_id,
            instance: @instance
          )

          if existing_field
            existing_field.update!(value: value)
          else
            @instance.project_instance_fields.create!(
              project_template_field_id: field_id,
              value: value
            )
          end
        end
      end
    rescue StandardError => e
      redirect_to course_topic_path(@course, @topic), alert: "Project update failed"
      return
    end

    redirect_to course_topic_path(@course, @topic), notice: "Project updated successfully."
  end


  def new
    authorize Topic
    @template_fields = @course.project_template.project_template_fields.where(applicable_to: [:topics, :both])

    if @template_fields.blank?
      redirect_to course_path(@course), alert: "Project template is missing or incomplete. Please set it up before creating a project."
      return
    end
  end

  def create
    begin
      ActiveRecord::Base.transaction do
        status = @course.require_coordinator_approval? ? :pending : :approved

        @topic = Topic.create!(
          course: @course,
          owner: current_user
        )

        title_value = nil

        params[:fields]&.each do |field_id, value|
          template_field = ProjectTemplateField.find(field_id)
          if template_field.label.strip.downcase.include?("title")
            title_value = value
          end
        end

        @instance = @topic.topic_instances.create!(
          version: 1,
          title: title_value,
          created_by: current_user,
          status: status
        )

        # saves all fields to the instance
        params[:fields]&.each do |field_id, value|
          template_field = ProjectTemplateField.find(field_id)

          @instance.project_instance_fields.create!(
            project_template_field: template_field,
            value: value
          )
        end
      end
    rescue StandardError => e
      redirect_to course_topic_path(@course, @topic), alert: "Topic creation failed"
      return
    end

    redirect_to course_topic_path(@course, @topic), notice: "Topic created!"
  end

  def destroy
    authorize @topic
    @topic.destroy
    redirect_to course_path(@course), notice: "Topic deleted"
  end

  private
  def search
    query = params[:query].to_s.downcase
    if query.present?
      @topics = @topics.select do |topic|
        latest = topic.topic_instances.order(version: :desc).first
        title = latest&.title&.downcase
        description = latest&.project_instance_fields
          &.includes(:project_template_field)
          &.find { |f| f.project_template_field.label.downcase.include?("description") }
          &.value&.downcase

        title&.include?(query) || description&.include?(query)
      end
    end
  end

  def set_course
    @course = Course.find(params[:course_id])
  end

  def set_topic
    @topic = @course.topics.find(params[:id])
  end

  def authorize_topic
    authorize @topic
  end
end

app/helpers/topics_helper.rb
module TopicsHelper
  def current_tab
    params[:tab] || 'details'
  end

  def show_progress_tab?
    @course.use_progress_updates && @current_instance.status == "approved"
  end
end

app/views/topics/_topbar.html.erb
<div class="topbar">
  <a href="<%= course_path(@course) %>"><%= current_user.username %>'s Course View</a>

  <% if policy(@course).update? %>
    <div class="topbar-actions">
      <a href="<%= settings_course_path(@course) %>" class="topbar-icon" title="Edit Course Settings">
        <%= image_tag "settings.svg" %>
        <span class="topbar-info">Edit Course Settings</span>
      </a>

      <a href="<%= edit_course_project_template_path(@course) %>" class="topbar-icon" title="Edit Project Templates">
        <%= image_tag "project_templates.svg" %>
        <span class="topbar-info">Edit Templates</span>
      </a>
    </div>
  <% end %>
</div>

app/views/topics/_topic_actions.html.erb
<section class="project-actions">
  <div class="action-group">
    <!-- Lecturer Edit Actions -->
    <% if members.include?(current_user) %>
      <% if policy(topic).update? && (current_version == latest_version) %>
        <div class="action-note"> Latest Version </div> <%= link_to "Edit Topic", edit_course_topic_path(course, topic) %> <%= image_tag("edit.svg") %>
      <% else %>
        <span class="action-note"><%= image_tag("lock.svg") %> Unable to Edit Topic</span>
      <% end %>
      
      <% if current_version == latest_version %>
      <%= button_to "Delete Topic", course_topic_path(course, topic), method: :delete, 
                  data: { confirm: "Are you sure you want to delete this topic?" },
                  class: "back-btn " %>
      <% end %>
    <% end %>
    
    <!-- Version Jump -->
    <% if current_version != latest_version %>
      <%= link_to "Jump to Current Version", course_topic_path(course, topic) %>
    <% end %>
  </div>
</section>

app/views/topics/_topic_comments.html.erb
<section class="project-comments" id="topic-comments">
  <header class="section-header">
    <h2 class="section-title">Comments</h2>
  </header>
  <div class="comments-container">
    <% if comments&.any? %>
      <div class="comments-list">
        <% comments.each do |comment| %>
          <article class="comment">
            <div class="comment-marker">
              <span class="user-badge"><%= comment.user.username[0].upcase %></span>
            </div>
            <div class="comment-body-wrapper">
              <header class="comment-header">
                <% if Current.user == comment.user %>
                  <h4 class="comment-author" style="color: green"><%= comment.user.username %></h4>
                <% else %>
                  <h4 class="comment-author"><%= comment.user.username %></h4>
                <% end %>
                <time class="comment-date">
                  <% if comment.created_at > 3.days.ago %>
                    <%= time_ago_in_words(comment.created_at) %> ago
                  <% else %>
                    <%= format_timestamp(comment.created_at) %>
                  <% end %>
                </time>
                <% if policy(comment).destroy? %>
                    <div class="comment-actions">
                      <%= link_to soft_delete_comment_path(comment),
                        data: { turbo_method: :patch, confirm: "Are you sure you want to delete this comment?" },
                        class: "delete-comment-btn",
                        title: "Delete comment" do %>
                        <span class="delete-icon">×</span>
                        <% end %>
                    </div>
                <% end %>
              </header>
              <div class="comment-body">
                <% if !comment.deleted %>
                  <%= simple_format(comment.text) %>
                <% else %>
                  <span class="deleted-comment">This comment was deleted</span>
                <% end %>
              </div>
            </div>
          </article>
        <% end %>
      </div>
    <% else %>
      <div class="no-comments">
        <p>There are no comments yet.</p>
      </div>
    <% end %>
    
    <% if policy(new_comment).create? %>
      <div class="comment-form-container">
        <%= form_with model: new_comment, local: true, class: "comment-form" do |form| %>
          <%= form.hidden_field :source_type, value: "TopicInstance" %>
          <%= form.hidden_field :source_id, value: current_instance_id %>
          
          <div class="form-group">
            <div class="comment-input-wrapper">
              <%= form.text_area :user_comment, class: "comment-textarea", rows: 4, placeholder: "add a comment..." %>
              <%= form.button class: "send-btn", type: "submit", title: "Send comment" do %>
                <%= image_tag "send.svg" %>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</section>

app/views/topics/_topic_fields.html.erb
  <section class="project-fields">
    <header class="section-header">
      <h2 class="section-title">Project Details</h2>
    </header>

    <div class="fields-container">
      <% fields.each do |field| %>
        <div class="field-row">
          <div class="field-label">
            <%= field.project_template_field.label %>
          </div>
          <div class="field-value">
            <% if field.value.present? %>
              <%
                if field.project_template_field.dropdown? || field.project_template_field.radio?
                  begin
                    parsed_value = JSON.parse(field.value)
                    display_value = parsed_value.is_a?(Array) ? parsed_value.join(", ") : parsed_value
                  rescue JSON::ParserError
                    display_value = field.value
                  end
                else
                  display_value = field.value
                end
              %>
              <%= display_value %>
            <% else %>
              No content provided
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </section>

<style>
  table, th, td, tr {
    border: 1px solid black;
    border-collapse: collapse;
    padding: 5px;
    vertical-align: top;
  }

  .diff ul {
    list-style: none;
  }

  .diff del, li.del{
    text-decoration: none;
    background-color:  #f4d4d4;
  }

  .diff ins, li.ins{
    text-decoration: none;
    background-color: #d4f4dd;
  }

  .ins-change{
    background-color: #77DD77;
  }

  .del-change{
  background-color: #FF6961;
  text-decoration: line-through;
  }

  li.empty {
  min-height: 1em;
  list-style: none;
}

  .placeholder {
  background-color: #e0e0e0;
  color: transparent;
  user-select: none;
}

  .diff li {
    list-style: none;
  }

  .diff li { border: 1px dashed rgba(0,0,0,0.1); }

  .diff-col {
  width: 50%;
  word-wrap: break-word;
  vertical-align: top;
}

</style>

<% if @index < @instances.size %>
  <h4>Comparison with next instance</h4>
  <br>

<table>
  <tr>
    <th>Field</th>
    <th>Deletions</th>
    <th>Additions</th>
  </tr>

  <% fields.zip(next_fields).each do |current_field, next_field| %>
    <% field_name = (current_field || next_field).project_template_field.label %>

    <% normalize = ->(text) do
         text.to_s
             .gsub(/\r\n?/, "\n")
             .gsub(/^$/, "[[EMPTYLINE]]")
       end %>

    <% old_val = normalize.call(current_field&.value) %>
    <% new_val = normalize.call(next_field&.value) %>

    <tr>
      <td><%= field_name %></td>

      <% if old_val != new_val %>
        <% old_lines = old_val.split("\n") %>
        <% new_lines = new_val.split("\n") %>

        <%# Use Diff::LCS to align line changes properly %>
        <% diffs = Diff::LCS.sdiff(old_lines, new_lines) %>

        <% aligned_left  = [] %>
        <% aligned_right = [] %>

        <% diffs.each do |change| %>
          <% case change.action %>
          <% when '=' %>
            <% line = h(change.old_element) %>
            <% aligned_left  << "<li class='unchanged'>#{line}</li>" %>
            <% aligned_right << "<li class='unchanged'>#{line}</li>" %>

          <% when '-' %>
            <% line = change.old_element.to_s %>
            <% if line.strip.empty? || line == "[[EMPTYLINE]]" %>
              <% aligned_left  << "<li class='del'><span class='del-change'><br></span></li>" %>
              <% aligned_right << "<li class='placeholder'><br></li>" %>
            <% else %>
              <% safe_line = h(change.old_element) %>
              <% aligned_left  << "<li class='del'><span class='del-change'>#{safe_line}</span></li>" %>
              <% aligned_right << "<li class='placeholder'>#{safe_line}</li>" %>
            <% end %>

          <% when '+' %>
            <% line = change.new_element.to_s %>
            <% if line.strip.empty? || line == "[[EMPTYLINE]]" %>
              <% aligned_left  << "<li class='placeholder'><br></li>" %>
              <% aligned_right << "<li class='ins'><span class='ins-change'><br></span></li>" %>
            <% else %>
              <% safe_line = h(change.new_element) %>
              <% aligned_left  << "<li class='placeholder'>#{safe_line}</li>" %>
              <% aligned_right << "<li class='ins'><span class='ins-change'>#{safe_line}</span></li>" %>
            <% end %>

          <% when '!' %>
            <% old_line = change.old_element.to_s %>
            <% new_line = change.new_element.to_s %>

            <%# 🔹 Do word-level diff inside this line %>
            <% old_words = old_line.split(/(\s+)/) %>
            <% new_words = new_line.split(/(\s+)/) %>
            <% word_diffs = Diff::LCS.sdiff(old_words, new_words) %>

          <% old_html = word_diffs.map do |w|
              case w.action
              when '='
                h(w.old_element)
              when '-', '!'
                "<span class='del-change'>#{h(w.old_element)}</span>"
              else
                ""
              end
            end.join %>

          <% new_html = word_diffs.map do |w|
              case w.action
              when '='
                h(w.new_element)
              when '+', '!'
                "<span class='ins-change'>#{h(w.new_element)}</span>"
              else
                ""
              end
            end.join %>

            <% aligned_left  << "<li class='del'>#{old_html}</li>" %>
            <% aligned_right << "<li class='ins'>#{new_html}</li>" %>
          <% end %>
        <% end %>

        <td class="diff-col">
          <ul class="diff">
            <%= aligned_left.join
                  .gsub('[[EMPTYLINE]]', '<br>')
                  .html_safe %>
          </ul>
        </td>

        <td class="diff-col">
          <ul class="diff">
            <%= aligned_right.join
                  .gsub('[[EMPTYLINE]]', '<br>')
                  .html_safe %>
          </ul>
        </td>

      <% else %>
        <td colspan="2" class="no_change">No changes</td>
      <% end %>
    </tr>
  <% end %>
</table>

<% end %>

app/views/topics/_topic_header.html.erb
<header class="project-header">
  <h1 class="project-title" id="topic-title"><%= current_instance.title %></h1>

  <div class="project-properties">
    <div class="properties-column properties-column-left">

      <!-- Type -->
      <div class="properties-item">
        <span class="properties-label"><%= image_tag("person.svg") %> Type</span>
        <span class="properties-value">
          <p>Topic</p>
        </span>
      </div>

      <!-- Owner -->
      <div class="properties-item owner-properties">
        <span class="properties-label"><%= image_tag("person.svg") %> Owner</span>
        <div class="properties-value">
          <% if owner.is_a?(User) %>
            <p class="owner-row">
              <span class="user-badge"><%= owner.username[0].upcase %></span>
              <%= owner.username %>
            </p>
          <% else %>
            <% topic.owner.users.each do |user| %>
              <p class="owner-row">
                <span class="user-badge"><%= user.username[0].upcase %></span>
                <%= user.username %>
              </p>
            <% end %>
          <% end %>
        </div>
      </div>

      <!-- Group Name (only if group project) -->
      <% if topic.owner.is_a?(ProjectGroup) %>
        <div class="properties-item">
          <span class="properties-label"><%= image_tag("group.svg") %> Group Name</span>
          <span class="properties-value">
            <%= @topic.owner.group_name %>
          </span>
        </div>
      <% end %>
    </div>

      <div class="properties-column properties-column-right">
        <!-- Status -->
        <div class="version-container">
          <div class="properties-item">
            <span class="properties-label"><%= image_tag("status.svg") %> Status</span>
            <div class="properties-value">
              <% if policy(topic).change_status? &&  current_version == latest_version %>
                <div class="status-control">
                  <%= form_with url: change_status_course_topic_path(@course, topic), method: :patch, local: true, class: "status-change-form" do |f| %>
                    <% statuses = TopicInstance.statuses.keys.without("not_submitted") %>
                    <%= f.select :status, options_for_select(statuses.map { |s| [s.humanize, s] }, current_instance.status), {}, class: "status-select status-#{@topic.status}" %>
                    <%= f.button type: "submit", class: "status-save-btn", title: "Save status" do %>
                      <%= image_tag("check.svg")%>
                    <% end %>
                  <% end %>
                </div>
              <% else %>
                <span class="properties-value status-select status-<%= current_instance.status %>">
                  <%= current_instance.status.humanize %>
                </span>
              <% end %>
            </div>
          </div>
        
          <div class="timestamp-info">
            <% if current_instance.last_status_change_time.present? %>
              <div class="timestamp"><%= format_timestamp(current_instance.last_status_change_time) || '-' %></div>
            <% end %>
            <div class="status-username">
              <% if @current_instance.last_status_change_by.present? %>
                  <span class="status-dot <%= current_instance.status %>"></span>
                  <%= username(current_instance.last_status_change_by) || 'Not changed' %>
              <% else %>
                <%= image_tag("pending.svg") %> Awaiting review
              <% end %>
            </div>
          </div>
        </div>

          <!-- Version Info with Navigation -->
          <div class="version-container">
            <div class="properties-item version-info">
              <span class="properties-label">
                <%= image_tag("version.svg") %> Version
                <% if current_version != latest_version %>
                  <em class="version-note">(older)</em>
                <% end %>
              </span>
              <div class="properties-value version-navigation">
                <% # Back arrow: older version (lower index) %>
                <% if current_version > 1 %>
                  <%= link_to course_topic_path(@course, topic, version: current_version - 1), class: "version-btn back-arrow" do %>
                    <%= image_tag("arrow_back.svg", class:"back-arrow") %>
                  <% end %>
                <% else %>
                  <span class="version-btn back-arrow disabled">
                    <%= image_tag("arrow_back.svg", class:"back-arrow") %>
                  </span>
                <% end %>

                <span class="version-text"><%= current_version %> of <%= instances.size %></span>

                <% # Next arrow: newer version (higher index) %>
                <% if current_version < instances.size %>
                  <%= link_to course_topic_path(@course, topic, version: current_version + 1), class: "version-btn next-arrow" do %>
                    <%= image_tag("arrow_forward.svg", class:"foward-arrow") %>
                  <% end %>
                <% else %>
                  <span class="version-btn next-arrow disabled">
                    <%= image_tag("arrow_forward.svg", class:"foward-arrow") %>
                  </span>
                <% end %>
              </div>
            </div>
            <div class="timestamp-info">
              <% if current_instance.last_edit_time.present? %>
                <div class="timestamp"><%= format_timestamp(current_instance.last_edit_time) || '-' %></div>
              <% end %>
              <div class="status-username">
                <% editor_id = current_instance.last_edit_by || current_instance.created_by_id %>
                <%= image_tag("edit.svg") %><%= username(editor_id) || 'Not changed' %>
              </div>
            </div>
          </div>
      </div>

  </div>
</header>

app/views/topics/index.html.erb
<% content_for :stylesheets do %>
  <%= stylesheet_link_tag "courses" %>
  <%= stylesheet_link_tag "tailwind", "new_tailwind" %>
<% end %>
<% content_for :no_sidebar, true %>
<% content_for :hide_toggler, true %>
<% breadcrumb :topics, @course %>
<% content_for :title,
"Topics List - #{@course.course_name.truncate(TITLE_NAME_LIMIT)} | ProPro" %>
<%= render "topbar", user: current_user %>

<main class="main">
  <header class="section-header">
    <h1>Topics for
      <%= @course.course_name %></h1>
  </header>

  <section class="search-bar-container mb-2">
    <%= form_with url: course_topics_path(@course), method: :get, local: true, class: "search-form" do %>
      <%= label_tag :query, "Search topics:", class: "search-label" %>
      <%= text_field_tag :query,
      params[:query],
      class: "search-input",
      placeholder: "Enter keyword...",
      autocomplete: "topics-search" %>
      <%= submit_tag "Search", class: "btn btn-secondary" %>
    <% end %>
  </section>

  <h5><%= tag.div(flash[:alert], style: "color:red") if flash[:alert] %></h5>
  <h5><%= tag.div(flash[:notice], style: "color:green") if flash[:notice] %></h5>

  <section class="topics-list" id="topics-list">
    <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6 w-full">
      <% if @topics.any? %>
        <%= render partial: "courses/topic_card", collection: @topics, as: :topic %>
      <% else %>
        <p class="empty-state">No topics found.</p>
      <% end %>
    </div>
  </section>

  <div class="form-actions">
    <%= link_to "Back to Course", course_path(@course), class: "btn-normal" %>
  </div>
</main>

<%= javascript_include_tag "courses", "data-turbo-track": "reload", defer: true %>