config/routes.rb
Rails.application.routes.draw do
  # Routes for static pages
  get 'privacy-policy', to: 'static_pages#privacy_policy', as: 'privacy_policy'
  get 'terms-of-service', to: 'static_pages#terms_of_service', as: 'terms_of_service'
  get 'about', to: 'static_pages#about'

  post 'user/create'
  get 'user/new_staff', to: 'user#new_staff', as: :new_staff
  get 'user/new_student', to: 'user#new_student', as: :new_student
  get 'user/profile'
  post 'user/edit'
  post 'user/:id/resend_invite', to: 'user#resend_invite', as: :resend_invite

  root 'homescreen#show'

  get 'login', to: 'sessions#new'
  resource :session

  resources :passwords, param: :token

  resources :comments, only: [:create] do
    member do
      patch 'soft_delete'
    end
  end

  resources :courses, only: %i[index show new create destroy] do
    member do
      get 'add_students'
      post 'handle_add_students'
      get 'add_lecturers'
      post 'handle_add_lecturers'
      get 'settings'
      post 'handle_settings'
      get 'export_csv'
      get 'profile/:participant_id/:participant_type', to: 'courses#profile', as: 'participant_profile'
      get 'details', to: 'courses#details'
      post 'import_details'
    end

    resources :projects, only: %i[show edit update create new] do
      member do
        patch :change_status
      end
      collection do
        get 'selected_topic', to: 'projects#selected_topic'
        get 'selected_topic_edit', to: 'projects#selected_topic_edit'
      end

      resources :progress_updates, only: %i[show edit update create new destroy]
    end

    resources :topics, only: %i[index show edit update create new destroy] do
      member do
        patch :change_status
      end
    end

    resources :participants, only: [:index]

    resources :lecturers, only: %i[index show] do
      member do
        patch 'promote_to_coordinator'
        patch 'demote_to_lecturer'
      end

      resources :projects, only: [:show], controller: 'projects'

      resources :topics, only: %i[index show edit update create new] do
        member do
          patch :change_status
        end
      end
    end

    resource :project_template, only: %i[edit update show]
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :sessions, dependent: :destroy

  normalizes :email_address, with: ->(e) { e.strip.downcase }
  normalizes :username, with: ->(n) { n.strip }

  has_many :enrolments, dependent: :destroy
  has_many :courses, through: :enrolments

  has_many :project_group_members
  has_many :project_groups, through: :project_group_members

  has_many :comments, dependent: :destroy
  has_one :otp, dependent: :destroy

  has_many :solo_projects, as: :owner, class_name: 'Project'
  has_many :group_projects, through: :project_groups, source: :project

  validates :email_address, presence: { message: 'cannot be empty' }, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }
  validates :password, length: { maximum: 72, message: 'must be less than 72 characters' }
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  allow_unauthenticated_access only: %i[new_staff new_student create]

  def resend_invite
    user = User.find(params[:id])
    if user.has_registered
      redirect_back_or_to '/', alert: 'User already registered'
      return
    end

    # Ensure OTP exists or recreate if missing (though it should exist for unregistered users)
    otp_instance = user.otp || Otp.create!(user: user, otp: SecureRandom.base64(8), token: SecureRandom.uuid)

    GeneralMailer.with(
      email_address: user.email_address,
      otp_token: otp_instance.token,
      otp: otp_instance.otp,
      is_staff: user.is_staff
    ).ProPro_Invite.deliver_later

    redirect_back_or_to '/', notice: "Invitation resent to #{user.email_address}"
  end

  def new_student
    @email = Otp.find_by(token: params[:token]).user.email_address
  rescue StandardError
    redirect_to login_path, alert: "Invalid token, perhaps you've already claimed your account? Try logging in."
  end

  def new_staff
    @email = Otp.find_by(token: params[:token]).user.email_address
  rescue StandardError
    redirect_to login_path, alert: "Invalid token, perhaps you've already claimed your account? Try logging in."
  end

  def edit
    unless Current.user.is_staff
      redirect_back_or_to '/', alert: 'Only staff can edit profiles'
      return
    end

    if params[:user][:username].blank?
      redirect_back_or_to '/', alert: 'Username cannot be empty'
      return
    end

    if params[:user][:new_password].present?
      if params[:user][:new_password_confirmation].blank? or params[:user][:new_password] != params[:user][:new_password_confirmation]
        redirect_back_or_to '/', alert: 'New passwords do not match'
        return
      elsif params[:user][:new_password].length > 72
        redirect_back_or_to '/', alert: 'Password must be less than 72 characters'
        return
      end
    end

    begin
      Current.user.update!(
        username: params[:user][:username],
        web_link: params[:user][:web_link],
        description: params[:user][:description]
      )

      Current.user.update!(password: params[:user][:new_password]) if params[:user][:new_password].present?
    rescue StandardError
      render :profile, status: :unprocessable_entity
      return
    end

    redirect_to user_profile_path, notice: 'Profile updated successfully'
  end

  def create
    response = params.permit(:password, :password_confirmation, :username, :token, :otp)
    return if response[:token].blank?

    if response[:otp].blank?
      redirect_back_or_to '/', alert: 'OTP cannot be empty'
      return
    end

    if response[:password].blank?
      redirect_back_or_to '/', alert: 'Password cannot be empty'
      return
    end

    if response[:password_confirmation].blank?
      redirect_back_or_to '/', alert: 'Password confirmation cannot be empty'
      return
    end

    if response[:password] != response[:password_confirmation]
      redirect_back_or_to '/', alert: 'Passwords are not the same'
      return
    end

    if response[:password].length > 72
      redirect_back_or_to '/', alert: 'Password must be less than 72 characters'
      return
    end

    otp_instance = Otp.find_by(token: response[:token], otp: response[:otp].strip)

    unless otp_instance
      redirect_back_or_to '/', alert: 'Something went wrong'
      return
    end

    user = otp_instance.user

    if response[:username].blank? && user.is_staff
      redirect_back_or_to '/', alert: 'Name cannot be empty'
      return
    end

    # ugly ik, whachu gonna do about it
    if !user.is_staff
      if user.update(has_registered: true, password: response[:password])
        redirect_to '/session/new', notice: 'Account successfully claimed'
      else
        redirect_back_or_to '/', alert: 'Something went wrong'
      end
    elsif user.update(has_registered: true, password: response[:password], username: response[:username].strip)
      redirect_to '/session/new', notice: 'Account successfully claimed'
    else
      redirect_back_or_to '/', alert: 'Something went wrong'
    end

    user.otp.destroy
  end

  def profile
    @user = Current.user
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/user/new.html.erb
<% content_for :stylesheets do %>
  <%= stylesheet_link_tag "tailwind", "new_tailwind" %>
<% end %>
<% content_for :title, "Log In | ProPro" %>
<% provide :no_footer, true %>

<div
  class="
    flex flex-col items-center justify-center min-h-[85vh] w-full px-4 pt-20
  "
>

  <h1
    class="
      text-3xl md:text-4xl font-bold text-gray-900 mb-6 mt-4 tracking-tight
    "
  >Welcome to ProPro</h1>

  <div
    class="
      w-full max-w-lg bg-white rounded-xl shadow-lg pt-4 p-8 border border-gray-100 pb-2
    "
  >

    <h2 class="text-2xl font-bold text-center text-gray-800 mb-3">Sign Up</h2>
    <% if flash[:notice] %>
      <div
        class="
          mb-6 mx-auto w-full bg-green-50 border-1 border-l-4 border-green-500
          text-green-700 p-4 rounded shadow-sm flex items-center animate-pulse
        "
        role="alert"
      >
        <svg
          class="w-5 h-5 mr-3 text-green-500 flex-shrink-0"
          fill="none"
          stroke="currentColor"
          viewBox="0 0 24 24"
        >
          <path
            stroke-linecap="round"
            stroke-linejoin="round"
            stroke-width="2"
            d="M5 13l4 4L19 7"
          />
        </svg>

        <div>
          <p class="font-bold text-sm">Success</p>
          <p class="text-sm"><%= flash[:notice] %></p>
        </div>
      </div>
    <% end %>

    <% if flash[:alert] %>
      <div
        class="
          mb-6 mx-auto w-full bg-red-50 border-1 border-l-4 border-red-500 text-red-700
          p-4 rounded shadow-sm flex items-center animate-pulse
        "
        role="alert"
      >
        <svg
          class="w-5 h-5 mr-3 text-red-500 flex-shrink-0"
          fill="none"
          stroke="currentColor"
          viewBox="0 0 24 24"
        ><path
            stroke-linecap="round"
            stroke-linejoin="round"
            stroke-width="2"
            d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z"
          /></svg>
        <div>
          <p class="font-bold text-sm">Sign Up Failed</p>
          <p class="text-sm"><%= flash[:alert] %></p>
        </div>
      </div>
    <% end %>

    <%= form_with url: session_path, class: "space-y-5" do |form| %>

      <div>
        <%= form.label :fullname, "Full Name" %>
        <%= form.text_field :fullname,
                            required: true,
                            autofocus: true,
                            placeholder: "Enter your full name",
                            value: params[:fullname],
                            class:
                            "w-full px-4 py-2.5 border border-gray-300 rounded-lg shadow-sm focus:ring-1 focus:ring-green-400 focus:border-green-400 outline-none transition-all text-gray-900 placeholder-gray-400" %>
        <%= form.label :email_address,
                   "Email Address",
                   class: "block text-md font-semibold text-gray-700 mb-1 mt-3" %>
        <%= form.email_field :email_address,
                         required: true,
                         autofocus: true,
                         autocomplete: "username",
                         placeholder: "Enter your email address",
                         value: params[:email_address],
                         class:
                           "w-full px-4 py-2.5 border border-gray-300 rounded-lg shadow-sm focus:ring-1 focus:ring-green-400 focus:border-green-400 outline-none transition-all text-gray-900 placeholder-gray-400" %>
      </div>

      <div style="margin-bottom: 0;">
        <div class="flex items-center justify-between mb-1">
          <%= form.label :password,
                     "Password",
                     class: "block text-md font-semibold text-gray-700" %>
        </div>
        <div data-controller="password-verify">
            <%= form.password_field :password,
                                required: true,
                                autocomplete: "new-password",
                                placeholder: "Enter your password",
                                data: { password_verify_target: "password", action: "input->password-verify#validate" },
                                class:
                                "w-full px-4 py-2.5 border border-gray-300 rounded-lg shadow-sm focus:ring-1 focus:ring-green-400 focus:border-green-400 outline-none transition-all text-gray-900 placeholder-gray-400" %>

            <div class="flex items-center justify-between mb-1 mt-2">
            <%= form.label :confirm_password,
                        "Confirm Password",
                        class: "block text-md font-semibold text-gray-700" %>
            </div>
            <%= form.password_field :confirm_password,
                                required: true,
                                autocomplete: "new-password",
                                placeholder: "Confirm password",
                                data: { password_verify_target: "confirm", action: "input->password-verify#validate" },
                                class:
                                "w-full px-4 py-2.5 border border-gray-300 rounded-lg shadow-sm focus:ring-1 focus:ring-green-400 focus:border-green-400 outline-none transition-all text-gray-900 placeholder-gray-400" %>
            <div data-password-verify-target="message" class="mt-1"></div>
        </div>
      </div>

      <div class="pt-2 mt-6 mb-2">
        <%= form.submit "Sign Up",
                    class:
                      "w-full bg-green-500 hover:bg-green-600 text-white font-bold py-3 px-4 rounded-lg cursor-pointer transition-colors shadow-md hover:shadow-lg text-lg" %>
      </div>
    <% end %>

  </div>
</div>

app/views/user/new_staff.html.erb
<% content_for :stylesheets do %>
  <%= stylesheet_link_tag "courses" %>
  <%= stylesheet_link_tag "tailwind", "new_tailwind" %>
<% end %>
<% content_for :title, "New Lecturer | ProPro" %>

<div class="main">
  <h1>New Staff</h1>
  <br>

  <div class="container">
    <h5><%= tag.div(flash[:alert], style: "color:red") if flash[:alert] %></h5>
    <h5><%= tag.div(flash[:notice], style: "color:green") if flash[:notice] %></h5>
    <br>

    <%= form_with url: user_create_path do |form| %>
      <%= form.hidden_field :token, value: params[:token] %>
      <%= form.search_field :email, value: @email, disabled: true %><br>
      <%= form.password_field :otp, required: true, placeholder: "OTP" %><br>
      <%= form.password_field :password, required: true, autocomplete: "current-password", placeholder: "Enter your password", maxlength: 72 %><br>
      <%= form.password_field :password_confirmation, required: true, placeholder: "Enter password confirmation", maxlength: 72 %><br>
      <%= form.search_field :username, placeholder: "Name", required: true %><br>
    <%= form.submit "Create Account" %>
    <% end %>
  </div>
</div>

app/views/user/new_student.html.erb
<% content_for :stylesheets do %>
  <%= stylesheet_link_tag "courses" %>
  <%= stylesheet_link_tag "tailwind", "new_tailwind" %>
<% end %>
<% content_for :title, "New Student | ProPro" %>

<div class="main">
  <h1>New Student</h1>
  <br>

  <div class="container">
    <h5><%= tag.div(flash[:alert], style: "color:red") if flash[:alert] %></h5>
    <h5><%= tag.div(flash[:notice], style: "color:green") if flash[:notice] %></h5>
    <br>

    <%= form_with url: user_create_path do |form| %>
      <%= form.hidden_field :token, value: params[:token] %>
      <%= form.search_field :email, value: @email, disabled: true %><br>
      <%= form.password_field :otp, required: true, placeholder: "OTP" %><br>
      <%= form.password_field :password, required: true, autocomplete: "current-password", placeholder: "Enter your password", maxlength: 72 %><br>
      <%= form.password_field :password_confirmation, required: true, placeholder: "Enter password confirmation", maxlength: 72 %><br>
    <%= form.submit "Create Account" %>
    <% end %>
  </div>
</div>

app/views/user/profile.html.erb
<% content_for :stylesheets do %>
  <%= stylesheet_link_tag "projects" %>
  <%= stylesheet_link_tag "tailwind", "new_tailwind" %>
<% end %>

<% content_for :title, "Edit Profile | ProPro" %>
  <main class="project-edit">
    <header class="edit-header">
      <div class="edit-header-row">
        <h1 class="edit-title">Edit Profile <%= image_tag("edit.svg") %></h1>
      </div>
      <p class="edit-description">Update your profile details and information below.</p>
    </header>

    <div class="fields-container">
      <h5><%= tag.div(flash[:alert], style: "color:red") if flash[:alert] %></h5>
      <h5><%= tag.div(flash[:notice], style: "color:green") if flash[:notice] %></h5>
    </div>

    <%= form_with url: user_edit_path, model: @user, method: :post, local: true, class: "edit-form" do |form| %>
      <div class="fields-container">
        <div class="account-details">
        <h4>Account details</h4>

        <div class="field-row">
          <%= form.label :username, "Username", class: "field-label" %>
          <%= form.text_field :username, class: "form-control" %>
        </div>

        <div class="field-row">
          <%= form.label :web_link, "Link to MMU directory/Portfolio", class: "field-label" %>
          <%= form.text_field :web_link, class: "form-control" %>
        </div>

        <div class="field-row">
          <%= form.label :description, "Description", class: "field-label" %>
          <p class="field-hint">Describe yourself to indicate to students what project topics you may accept for the courses you are teaching. Also indicate Consultation Hours (days of week and time) when students can meet you to request you as supervisor in case of FYP/Mini IT Project.</p>
          <%= form.text_area :description, class: "form-control" %>
        </div>
        </div>

        <div class="change-password">
        <h4>Change password</h4>

        <div class="field-row">
          <%= form.label :new_password, "New Password", class: "field-label" %>
          <%= form.password_field :new_password, class: "form-control" %>
        </div>

        <div class="field-row">
          <%= form.label :new_password_confirmation, "New Password Confirmation", class: "field-label" %>
          <%= form.password_field :new_password_confirmation, class: "form-control" %>
        </div>
        </div>
      </div>

      <div class="form-actions">
        <%= link_to "← Back", "/", class: "btn btn-secondary" %>
        <%= form.submit "Save changes", class: "btn btn-primary" %>
      </div>
    <% end %>
  </main>